# Exported from Render on 2025-01-30T18:46:16Z
services:
  - type: web
    name: TODO-MERN-APP-Frontend
    runtime: static
    repo: https://github.com/yeritsyan/TODO-MERN-APP
    envVars:
      - key: VITE_BACKEND_URL
        sync: false
    buildCommand: npm run build
    staticPublishPath: dist
    rootDir: frontend
version: "1"
