# Exported from Render on 2025-01-30T18:51:05Z
services:
  - type: web
    name: TODO-MERN-APP
    runtime: node
    repo: https://github.com/yeritsyan/TODO-MERN-APP
    plan: free
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: DB_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
    region: frankfurt
    buildCommand: npm run setup
    startCommand: npm run start
    rootDir: backend
version: "1"
